#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source lfcd
LFCD="$HOME/.config/lf/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

# Run Starship shell prompt
eval "$(starship init zsh)"

# Define custom aliases
alias nv="nvim"
alias lf="lfcd"
alias lgt="lazygit"
alias zshconfig="nvim ~/.config/zsh/.zprezto/runcoms/zshrc"
alias reboot="loginctl reboot"
alias suspend="loginctl suspend"
