#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Add directories to path
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Run Starship shell prompt
eval "$(starship init zsh)"

# Define custom aliases
alias nv="nvim"
alias lgt="lazygit"
alias zshconfig="nvim ~/.config/zsh/.zprezto/runcoms/zshrc"
alias reboot="loginctl reboot"
alias suspend="loginctl suspend"
